version: '3.8'

services:
  postgres:
    image: postgres:latest
    volumes:
      - dbdata:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: "pass"
    ports:
      - "5432:5432"

volumes:
  dbdata: